services:
  # Database
  db:
    image: postgres:15-alpine
    container_name: elysian-realm-db
    restart: always
    environment:
      POSTGRES_DB: elysian-realm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: elysian-realm-jaeger
    restart: always
    ports:
      - '6831:6831/udp'   # Jaeger agent
      - '6832:6832/udp'   # Jaeger collector
      - '16686:16686'     # Jaeger UI
      - '14268:14268'     # Jaeger collector HTTP
      - '4317:4317'       # OTLP gRPC
      - '4318:4318'       # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:14269/"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elysian-realm-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
      jaeger:
        condition: service_started
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/elysian-realm?schema=public
      - JWT_SECRET=supersecretkey
      - REFRESH_TOKEN_SECRET=supersecretrefreshtokenkey
      - ACCESS_TOKEN_EXPIRES_IN=5m
      - REFRESH_TOKEN_EXPIRES_IN=60d
      - OTEL_SERVICE_NAME=elysian-realm-backend
      - OTEL_EXPORTER_TYPE=otlp
      - OTEL_OTLP_ENDPOINT=http://jaeger:4318/v1/traces
      - OTEL_LOG_LEVEL=debug
    ports:
      - '3000:3000'
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: elysian-realm-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data: