// English translations
export default {
  success: "Success",
  error: "Error",
  validation_error: "Validation Error",
  not_found: "Not found",
  resource_not_found: "Resource not found",
  internal_server_error: "Internal server error",
  unexpected_error: "An unexpected error occurred",

  auth: {
    user_created: "User created successfully",
    user_updated: "User updated successfully",
    user_deleted: "User deleted successfully",
    role_created: "Role created successfully",
    role_updated: "Role updated successfully",
    role_deleted: "Role deleted successfully",
    auth_success: "Authentication successful",
    invalid_credentials: "Invalid credentials",
    token_expired: "Token has expired",
    access_denied: "Access denied",
    permission_required: "Insufficient permissions",
    email_required: "Email is required",
    password_required: "Password is required",
    invalid_email: "Email must be a valid email address",
    password_min_length: "Password must be at least 8 characters",
    name_required: "Name is required",
    role_required: "Role is required",
    login_successful: "Login successful",
    token_refreshed_successfully: "Token refreshed successfully",
    invalid_refresh_token: "Invalid refresh token",
    user_not_found: "User not found",
    failed_to_refresh_token: "Failed to refresh token",
    email_does_not_match_authenticated_user: "Email does not match authenticated user",
    passkeys_retrieved_successfully: "Passkeys retrieved successfully",
    passkey_deleted_successfully: "Passkey deleted successfully",
    authentication_options_generated_successfully: "Authentication options generated successfully",
    passwordless_authentication_options_generated_successfully: "Passwordless authentication options generated successfully",
    user_not_found_error: "User not found",
    passkey_registered_successfully: "Passkey registered successfully",
    unauthorized: "Unauthorized",
    passkey_not_found: "Passkey not found",
    authentication_failed: "Authentication failed",
    failed_to_verify_authentication_response: "Failed to verify authentication response",
    no_authentication_challenge_found: "No authentication challenge found",
    failed_to_generate_passwordless_authentication_options: "Failed to generate passwordless authentication options",
    no_passkeys_found_for_this_user: "No passkeys found for this user",
    failed_to_generate_authentication_options: "Failed to generate authentication options",
    email_required_for_email_based_authentication: "Email is required for email-based authentication",
    failed_to_verify_registration_response: "Failed to verify registration response",
    passkey_verification_failed: "Passkey verification failed",
    no_registration_challenge_found: "No registration challenge found",
    failed_to_generate_registration_options: "Failed to generate registration options",
    registration_options_generated_successfully: "Registration options generated successfully",
    failed_to_retrieve_passkeys: "Failed to retrieve passkeys",
    failed_to_delete_passkey: "Failed to delete passkey",
  },
  admin: {
    admins_retrieved_successfully: "Admins retrieved successfully",
    admin_retrieved_successfully: "Admin retrieved successfully",
    admin_not_found: "Admin not found",
    admin_updated_successfully: "Admin updated successfully",
    failed_to_update_admin: "Failed to update admin",
    admin_created_successfully: "Admin created successfully",
    failed_to_create_admin: "Failed to create admin",
    admin_deleted_successfully: "Admin deleted successfully",
    failed_to_delete_admin: "Failed to delete admin",
    roles_retrieved_successfully: "Roles retrieved successfully",
    role_created_successfully: "Role created successfully",
    failed_to_create_role: "Failed to create role",
    role_updated_successfully: "Role updated successfully",
    failed_to_update_role: "Failed to update role",
    role_deleted_successfully: "Role deleted successfully",
    failed_to_delete_role: "Failed to delete role",
    permissions_retrieved_successfully: "Permissions retrieved successfully",
    unauthorized: "Unauthorized",
    forbidden_insufficient_permissions: "Forbidden: Insufficient permissions",
  },
  audit: {
    audit_trails_retrieved_successfully: "Audit trails retrieved successfully",
    audit_trail_retrieved_successfully: "Audit trail retrieved successfully",
    user_audit_trails_retrieved_successfully: "User audit trails retrieved successfully",
    entity_audit_trails_retrieved_successfully: "Entity audit trails retrieved successfully",
    audit_trail_not_found: "Audit trail not found",
  },

  // Validation error messages
  validation: {
    string_format: "Property '{{field}}' format error",
    string_format_email: "Property '{{field}}' must be a valid email address",
    string_format_uuid: "Property '{{field}}' must be a valid UUID",
    string_format_uri: "Property '{{field}}' must be a valid URI",
    string_format_datetime: "Property '{{field}}' must be a valid ISO 8601 date-time",
    string_min_length: "Property '{{field}}' must be at least {{minLength}} characters",
    string_max_length: "Property '{{field}}' must be no more than {{maxLength}} characters",
    string_pattern: "Property '{{field}}' must match the required pattern",
    required_property: "Property '{{field}}' is required",
    string_type: "Property '{{field}}' must be a string",
    number_type: "Property '{{field}}' must be a number",
    boolean_type: "Property '{{field}}' must be a boolean",
    array_type: "Property '{{field}}' must be an array",
    array_min_items: "Property '{{field}}' must have at least {{minItems}} items",
    array_max_items: "Property '{{field}}' must have no more than {{maxItems}} items"
  }
} as const;