// Indonesian translations
export default {
  success: "Berhasil",
  error: "Kesalahan",
  validation_error: "Kesalahan Validasi",
  not_found: "Tidak ditemukan",
  resource_not_found: "Sumber daya tidak ditemukan",
  internal_server_error: "Kesalahan server internal",
  unexpected_error: "Terjadi kesalahan yang tidak terduga",

  auth: {
    user_created: "Pengguna berhasil dibuat",
    user_updated: "Pengguna berhasil diperbarui",
    user_deleted: "Pengguna berhasil dihapus",
    role_created: "Peran berhasil dibuat",
    role_updated: "Peran berhasil diperbarui",
    role_deleted: "Peran berhasil dihapus",
    auth_success: "Autentikasi berhasil",
    invalid_credentials: "Kredensial tidak valid",
    token_expired: "Token telah kedaluwarsa",
    access_denied: "Akses ditolak",
    permission_required: "Izin tidak mencukupi",
    email_required: "Email wajib diisi",
    password_required: "Kata sandi wajib diisi",
    invalid_email: "Email harus merupakan alamat email yang valid",
    password_min_length: "Kata sandi harus minimal 8 karakter",
    name_required: "Nama wajib diisi",
    role_required: "Peran wajib diisi",
    login_successful: "Login berhasil",
    token_refreshed_successfully: "Token berhasil diperbarui",
    invalid_refresh_token: "Token refresh tidak valid",
    user_not_found: "Pengguna tidak ditemukan",
    failed_to_refresh_token: "Gagal memperbarui token",
    email_does_not_match_authenticated_user: "Email tidak cocok dengan pengguna yang diautentikasi",
    passkeys_retrieved_successfully: "Passkey berhasil diambil",
    passkey_deleted_successfully: "Passkey berhasil dihapus",
    authentication_options_generated_successfully: "Opsi autentikasi berhasil dihasilkan",
    passwordless_authentication_options_generated_successfully: "Opsi autentikasi tanpa kata sandi berhasil dihasilkan",
    user_not_found_error: "Pengguna tidak ditemukan",
    passkey_registered_successfully: "Passkey berhasil didaftarkan",
    unauthorized: "Tidak diizinkan",
    passkey_not_found: "Passkey tidak ditemukan",
    authentication_failed: "Autentikasi gagal",
    failed_to_verify_authentication_response: "Gagal memverifikasi respons autentikasi",
    no_authentication_challenge_found: "Tidak ditemukan tantangan autentikasi",
    failed_to_generate_passwordless_authentication_options: "Gagal menghasilkan opsi autentikasi tanpa kata sandi",
    no_passkeys_found_for_this_user: "Tidak ditemukan passkey untuk pengguna ini",
    failed_to_generate_authentication_options: "Gagal menghasilkan opsi autentikasi",
    email_required_for_email_based_authentication: "Email diperlukan untuk autentikasi berbasis email",
    failed_to_verify_registration_response: "Gagal memverifikasi respons pendaftaran",
    passkey_verification_failed: "Verifikasi passkey gagal",
    no_registration_challenge_found: "Tidak ditemukan tantangan pendaftaran",
    failed_to_generate_registration_options: "Gagal menghasilkan opsi pendaftaran",
    registration_options_generated_successfully: "Opsi pendaftaran berhasil dihasilkan",
    failed_to_retrieve_passkeys: "Gagal mengambil passkey",
    failed_to_delete_passkey: "Gagal menghapus passkey",
  },
  admin: {
    admins_retrieved_successfully: "Admin berhasil diambil",
    admin_retrieved_successfully: "Admin berhasil diambil",
    admin_not_found: "Admin tidak ditemukan",
    admin_updated_successfully: "Admin berhasil diperbarui",
    failed_to_update_admin: "Gagal memperbarui admin",
    admin_created_successfully: "Admin berhasil dibuat",
    failed_to_create_admin: "Gagal membuat admin",
    admin_deleted_successfully: "Admin berhasil dihapus",
    failed_to_delete_admin: "Gagal menghapus admin",
    roles_retrieved_successfully: "Peran berhasil diambil",
    role_created_successfully: "Peran berhasil dibuat",
    failed_to_create_role: "Gagal membuat peran",
    role_updated_successfully: "Peran berhasil diperbarui",
    failed_to_update_role: "Gagal memperbarui peran",
    role_deleted_successfully: "Peran berhasil dihapus",
    failed_to_delete_role: "Gagal menghapus peran",
    permissions_retrieved_successfully: "Izin berhasil diambil",
    unauthorized: "Tidak diizinkan",
    forbidden_insufficient_permissions: "Terlarang: Izin tidak mencukupi",
  },
  audit: {
    audit_trails_retrieved_successfully: "Catatan audit berhasil diambil",
    audit_trail_retrieved_successfully: "Catatan audit berhasil diambil",
    user_audit_trails_retrieved_successfully: "Catatan audit pengguna berhasil diambil",
    entity_audit_trails_retrieved_successfully: "Catatan audit entitas berhasil diambil",
    audit_trail_not_found: "Catatan audit tidak ditemukan",
  },

  // Validation error messages
  validation: {
    string_format: "Properti '{{field}}' format error",
    string_format_email: "Properti '{{field}}' harus merupakan alamat email yang valid",
    string_format_uuid: "Properti '{{field}}' harus merupakan UUID yang valid",
    string_format_uri: "Properti '{{field}}' harus merupakan URI yang valid",
    string_format_datetime: "Properti '{{field}}' harus merupakan tanggal-waktu ISO 8601 yang valid",
    string_min_length: "Properti '{{field}}' harus minimal {{minLength}} karakter",
    string_max_length: "Properti '{{field}}' harus maksimal {{maxLength}} karakter",
    string_pattern: "Properti '{{field}}' harus sesuai dengan pola yang diperlukan",
    required_property: "Properti '{{field}}' wajib diisi",
    string_type: "Properti '{{field}}' harus berupa teks",
    number_type: "Properti '{{field}}' harus berupa angka",
    boolean_type: "Properti '{{field}}' harus berupa boolean",
    array_type: "Properti '{{field}}' harus berupa array",
    array_min_items: "Properti '{{field}}' harus memiliki minimal {{minItems}} item",
    array_max_items: "Properti '{{field}}' harus memiliki maksimal {{maxItems}} item"
  }
} as const;